# Generated by Django 4.2.6 on 2023-10-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dandaprojects',
            name='image',
            field=models.CharField(default='https://images.unsplash.com/photo-1697641665161-48344289a88f?auto=format&fit=crop&q=80&w=1974&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', max_length=300),
        ),
    ]
