# Generated by Django 4.2.6 on 2023-11-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dandaprojects_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dandaprojects',
            name='description',
            field=models.CharField(default='NO DESCRIPTION YET', max_length=3000),
        ),
        migrations.AlterField(
            model_name='dandaprojects',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
