# Generated by Django 4.2.6 on 2023-11-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dandaprojects_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dandaprojects',
            name='category',
            field=models.CharField(default='TEASER', max_length=200),
        ),
    ]
