# Generated by Django 4.2.6 on 2023-12-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_frames'),
    ]

    operations = [
        migrations.AddField(
            model_name='dandaprojects',
            name='client',
            field=models.CharField(default='PLAYZ', max_length=200),
        ),
        migrations.AlterField(
            model_name='dandaprojects',
            name='category',
            field=models.CharField(max_length=200),
        ),
    ]
